OOS_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from em16.views import IndexRedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^em16/', include('em16.urls', namespace='em16')),
    url(r'^$', IndexRedirectView.as_view())

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

em16/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [

    # index
    url(r'^$', views.GameListView.as_view(), name="index"),

    # /teams/
    url(r'^teams/$', views.TeamListView.as_view(), name="team-list"),
    url(r'^teams/(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name="team-detail"),

    # /rounds/
    url(r'^rounds/(?P<pk>\d+)/$', views.RoundDetailView.as_view(), name="round-detail"),

    # /stadiums/
    url(r'^stadiums/', views.StadiumList.as_view(), name="stadium-list"),

    # /groups/
    url(r'^settings/groups/$', views.GroupListView.as_view(), name="group-list"),


    # /settings/
    url(r'^settings/$', views.SettingsView.as_view(), name="setting-list"),

    # /settings/team/
    url(r'^settings/team/add/$', views.TeamCreateView.as_view(), name="team-create"),
    url(r'^settings/team/$', views.SettingsTeamEditView.as_view(), name="team-edit"),
    url(r'^settings/team/(?P<pk>\d+)/delete/$', views.TeamDeleteView.as_view(), name="team-delete"),
    url(r'^settings/team/(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name="team-update"),

    # /settings/team/player
    url(r'^settings/team/(?P<pk>\d+)/player/add/$', views.PlayerCreateView.as_view(), name="player-create"),
    url(r'^settings/team/player/(?P<pk>\d+)/delete/$', views.PlayerDeleteView.as_view(), name="player-delete"),
    url(r'^settings/team/player/(?P<pk>\d+)/update/$', views.PlayerUpdateView.as_view(), name="player-update"),

    # /settings/game
    url(r'^settings/game/add/$', views.GameCreateView.as_view(), name="game-create"),
    url(r'^settings/game/$', views.SettingsGameEditView.as_view(), name="game-edit"),
    url(r'^settings/game/(?P<pk>\d+)/delete/$', views.GameDeleteView.as_view(), name="game-delete"),
    url(r'^settings/game/(?P<pk>\d+)/update/$', views.GameUpdateView.as_view(), name="game-update"),

    # /settings/group/
    url(r'^settings/group/$', views.SettingsGroupEditView.as_view(), name="group-edit"),
    url(r'^settings/group/team/(?P<pk>\d+)/update/$', views.GroupUpdateView.as_view(), name="group-update"),


]

em16/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


# media/img/flags/name
def upload_to_dir(instance, filename):
    return 'img/flags/{0}/{1}'.format(instance.name, filename)


# media/img/player/name
def upload_to_dir_player(instance, filename):
    return 'img/player/{0}/{1}'.format(instance.team, filename)


class Stadium(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    capacity = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["city"]


class Round (models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=1)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Team(models.Model):

    name = models.CharField(max_length=50, unique=True, blank=False, verbose_name="Team")
    short = models.CharField(max_length=3, default='')
    trainer = models.CharField(max_length=100)
    group = models.ForeignKey(Group, verbose_name="Gruppe", related_name='group')
    flag = models.ImageField(upload_to=upload_to_dir, default='', verbose_name="Nationalflagge")
    games_played = models.PositiveIntegerField(default=0)
    win = models.PositiveIntegerField(default=0)
    draw = models.PositiveIntegerField(default=0)
    lost = models.PositiveIntegerField(default=0)
    goal = models.PositiveIntegerField(default=0)
    goal_conceded = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('em16:team-detail', kwargs={'pk': self.pk})

    def _calc_tordifferenz(self):
        """returns the calculated Tordifferenz"""
        return self.goal - self.goal_conceded

    def _calc_points(self):
        return self.win * 3 + self.draw

    tordifferenz = property(_calc_tordifferenz)
    points = property(_calc_points)

    class Meta:
        ordering = ["name"]


class Player (models.Model):

    POSITION_CHOICES = (
        ('Torwart', 'Torwart'),
        ('Stürmer', 'Stürmer'),
        ('Mittelfeld', 'Mittelfeld'),
        ('Verteidigung', 'Verteidigung')
    )

    name = models.CharField(max_length=100, verbose_name='Vorname')
    surname = models.CharField(max_length=100, verbose_name='Nachname')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name='Nationalmannschaft', related_name='team')
    position = models.CharField(max_length=20, choices=POSITION_CHOICES, default='--', verbose_name='Position')
    number = models.IntegerField(default=0, verbose_name='Nummer')
    img = models.ImageField(upload_to=upload_to_dir_player, verbose_name='Spielerbild')

    def get_absolute_url(self):
        return reverse('em16:player-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return u"{0} {1}".format(self.surname, self.name)

    class Meta:
        ordering = ["surname"]


class Game(models.Model):
    date = models.DateField(auto_now=False, auto_now_add=False)
    time = models.TimeField(auto_now=False, auto_now_add=False)
    round = models.ForeignKey(Round, related_name='rounds')
    group = models.ForeignKey(Group, null=True, blank=True)
    teamHomeAlias = models.CharField(max_length=50, null=True, verbose_name='Heimteam Liste')
    teamGuestAlias = models.CharField(max_length=50, null=True, verbose_name='Gastteam Liste')
    host = models.ForeignKey(Stadium, verbose_name="Gastgeber", related_name='stadiums', default='')
    teamHome = models.ForeignKey(Team, related_name='home', null=True, blank=True)
    teamGuest = models.ForeignKey(Team, related_name='guest', null=True, blank=True)
    teamHomeGoals = models.PositiveIntegerField(null=True, blank=True)
    teamGuestGoals = models.PositiveIntegerField(null=True, blank=True)
    others = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return 'u{0}'.format(self.date)

    class Meta:
        ordering = ["date", "time"]

em16/forms.py
from django import forms
from em16.models import Game


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['date', 'time', 'round', '' 'group', 'teamHomeAlias', 'teamGuestAlias', 'host']

        widgets = {
            'date': forms.SelectDateWidget(),

        }

em16/views.py
from django.views import generic
from django.core.urlresolvers import reverse_lazy

from em16.models import Team, Player, Stadium, Game, Round, Group
from em16.forms import GameForm


# Create your views here.

class IndexRedirectView(generic.RedirectView):
    """A view that redirects to /em16/."""

    url = reverse_lazy('em16:index')


class TeamListView(generic.ListView):
    """A view of all teams."""

    template_name = 'em16/team-list.html'
    model = Team
    context_object_name = "teams"


class TeamDetailView(generic.DetailView):
    """A view of one team and related players"""

    model = Team
    template_name = 'em16/team-detail.html'

    def get_context_data(self, **kwargs):
        context = super(TeamDetailView, self).get_context_data(**kwargs)
        # context['players'] = Player.objects.filter(team_id=self.kwargs['pk']).order_by('team', 'surname')
        context['players'] = Player.objects.filter(team_id=self.kwargs['pk']).order_by('surname')
        return context


class TeamCreateView(generic.CreateView):
    """A view with a empty form to create a new team
       by success redirect to all teams
    """

    template_name = 'em16/forms/team_form.html'
    model = Team
    fields = ['name', 'short', 'group', 'trainer', 'flag']
    success_url = reverse_lazy('em16:team-list')


class TeamUpdateView(generic.UpdateView):
    """A view with a filled form to update a existing team
        by success redirect to settings of teams
    """

    model = Team
    template_name = 'em16/forms/team_update_form.html'
    fields = ['name', 'short', 'group', 'trainer', 'flag']
    success_url = reverse_lazy('em16:team-edit')


class TeamDeleteView(generic.DeleteView):
    """A view to delete existing team
        by success redirect to settings of teams
    """

    template_name = "em16/confirm/team_confirm_delete.html"
    model = Team
    success_url = reverse_lazy('em16:team-edit')


class PlayerCreateView(generic.CreateView):
    """A view with a empty form to create a new player to a certain team
        by success redirect to settings of teams
     """

    template_name = 'em16/forms/player_form.html'
    model = Player
    fields = ['team', 'name', 'surname', 'position', 'number', 'img']
    success_url = reverse_lazy('em16:team-edit')

    def get_initial(self):
        team = Team.objects.get(id=self.kwargs['pk'])
        return {
            'team': team,
        }


class PlayerUpdateView(generic.UpdateView):
    """A view with a filled form to update a existing player
        by success redirect to settings of teams
    """

    model = Player
    template_name = 'em16/forms/player_update_form.html'
    fields = ['team', 'name', 'surname', 'position', 'number', 'img']
    success_url = reverse_lazy('em16:team-edit')


class PlayerDeleteView(generic.DeleteView):
    """A view to delete existing player
        by success redirect to settings of teams
    """

    template_name = "em16/confirm/player_confirm_delete.html"
    model = Player
    success_url = reverse_lazy('em16:team-edit')


class GameListView(generic.ListView):
    template_name = 'em16/game_list.html'
    model = Game
    context_object_name = 'games'

    def get_context_data(self, **kwargs):
        context = super(GameListView, self).get_context_data(**kwargs)
        context['teams'] = Team.objects.all().order_by('group_id','-win', '-goal', 'goal_conceded')
        context['rounds'] = Round.objects.all()
        return context


class RoundDetailView(generic.DetailView):
    template_name = 'em16/round-detail.html'
    model = Round
    context_object_name = 'round'

    def get_context_data(self, **kwargs):
        context = super(RoundDetailView, self).get_context_data(**kwargs)
        context['rounds'] = Round.objects.all()
        context['games'] = Game.objects.filter(round_id=self.kwargs['pk']).order_by('date', 'time')
        return context


class GameCreateView(generic.CreateView):
    """A view with a empty form to create a new team
       by success redirect to all teams
    """

    template_name = 'em16/forms/game_form.html'
    form_class = GameForm
    success_url = reverse_lazy('em16:setting-list')


class GameUpdateView(generic.UpdateView):
    """A view with a empty form to create a new team
       by success redirect to all teams
    """
    model = Game
    template_name = 'em16/forms/game_update_form.html'
    fields = ['date', 'time', 'round', 'group', 'teamHome', 'teamGuest', 'teamHomeGoals', 'teamGuestGoals', 'others']
    success_url = reverse_lazy('em16:game-edit')


class GameDeleteView(generic.DeleteView):
    """A view to delete existing player
        by success redirect to settings of teams
    """

    template_name = "em16/confirm/game_confirm_delete.html"
    model = Game
    success_url = reverse_lazy('em16:game-edit')


class SettingsView(generic.TemplateView):
    """A view for all settings
     """

    template_name = 'em16/settings.html'


class SettingsTeamEditView(generic.ListView):
    """A view for all settings to all teams
     """

    template_name = 'em16/settings-team-edit.html'
    model = Team
    context_object_name = "teams"

    def get_context_data(self, **kwargs):
        context = super(SettingsTeamEditView, self).get_context_data(**kwargs)
        # context['players'] = Player.objects.all().order_by('team', 'surname')
        context['players'] = Player.objects.select_related('team').order_by('team', 'surname')
        return context


class SettingsGameEditView(generic.ListView):
    """A view for all settings to game schedule
     """

    template_name = 'em16/settings-game-edit.html'
    model = Game
    context_object_name = "games"


class SettingsGroupEditView(generic.ListView):
    """A view for all settings for groups
     """

    template_name = 'em16/settings-group-edit.html'
    model = Group
    context_object_name = "groups"

    def get_context_data(self, **kwargs):
        context = super(SettingsGroupEditView, self).get_context_data(**kwargs)
        context['teams'] = Team.objects.select_related('group').order_by('group', '-win', '-goal', 'goal_conceded')
        return context


class GroupListView(generic.ListView):
    """A view for all settings for groups
     """
    template_name = 'em16/group_list.html'
    model = Group
    context_object_name = "groups"

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        context['teams'] = Team.objects.select_related('group').order_by('group', '-win', '-goal', 'goal_conceded')
        context['games'] = Game.objects.all().order_by('group', 'date')
        return context


class GroupUpdateView(generic.UpdateView):
    """A view with a empty form to create a new team
       by success redirect to all teams
    """
    model = Team
    template_name = 'em16/forms/group_update_form.html'
    fields = ['games_played', 'win', 'draw', 'lost', 'goal', 'goal_conceded']
    success_url = reverse_lazy('em16:group-edit')


class StadiumList(generic.ListView):
    """A view of all stadiums."""

    template_name = 'em16/stadium-list.html'
    model = Stadium
    context_object_name = "stadiums"

em16/templates/em16/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="de" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Übersicht zur EM 2016 in Frankreich">
    <meta name="author" content="Katja Fräger">
    {% block head %}
        <title> EM 2016 in Frankreich</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>


</head>
<body>
<div class="container-fluid">
    <header class="container-fluid">
        <div class="col-lg-9">
            <h1>Europameisterschaft 2016 | Frankreich</h1>
            <nav class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'em16:index' %}">Spiele</a></li>
                    <li><a href="{% url 'em16:group-list' %}">Gruppen</a></li>
                    <li><a href="{% url 'em16:team-list' %}">Teams</a></li>
                    <li><a href="{% url 'em16:stadium-list' %}">Spielstätten</a></li>
                </ul>
            </nav>
        </div>
        <div class="col-lg-3">
            <img src="{% static 'img/logo.png' %}" alt="Logo EM 2016 Frankreich"/>
        </div>

    </header>
    <!-- Begin page content -->
    <div class="container-fluid main">
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer navbar-fixed-bottom">
        <div class="container">
            {% block footer %}
                <div class="col-lg-8">
                    <p>Katja Fräger &emsp;|&emsp; Objektorientiere Programmierung SS 2016 &emsp;|&emsp; Django - Projekt
                        | <span class="small">alle Bilder by UEFA.com</span></p>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'em16:setting-list' %}">&ensp;Einstellungen<i
                            class="glyphicon glyphicon-cog"></i></a>
                </div>
            {% endblock %}
        </div>
    </div>
</div>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

em16/templates/em16/game_list.html
{% extends "em16/base.html" %}
{% load staticfiles %}

{% block head %}
    {% with games|first as game_round %}
        <title> {{ game_round.round.name }} - EM 2016 in Frankreich</title>
    {% endwith %}
{% endblock %}

{% block content %}

    <div class="row title">
        <h5><a href="{% url 'em16:index' %}">Spiele</a> >> Überblick</h5>
    </div>
    <div class="row">
        <div class="row">
            {% include 'em16/include/nav_round_snippet.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 ">
            <h4 class="index-h4">Gruppenphase</h4>
            {% regroup teams by group as groups_list %}
            {% for group in groups_list %}
                <div class="home-group">
                    <div class="row">
                        <a href="{% url 'em16:group-list' %}">
                            <h4 class="text-center">{{ group.grouper }}</h4></a>
                        <hr>
                    </div>
                    <div class="row">
                        <div class="col-lg-9 col-lg-offset-2">
                            {% for team in group.list %}
                                <p>{{ forloop.counter }}.&emsp;
                                    <a href="{% url 'em16:team-detail' team.id %}" title="{{ team.name }}">
                                        <img class="flag_small" src="{{ team.flag.url }}" alt="{{ team.short }}"/>
                                    </a>
                                    {{ team.short }}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <p></p>
        </div>
    </div>
    {% for round in rounds %}
        <div class="row">
            <div class="col-lg-12 ">
                {% if round.name|slice:":1" == 'G' %}
                {% else %}
                    <h4 class="index-h4">{{ round.name }}</h4>
                    <table class="table-index-round-main">
                        <tr>
                            {% for game in games %}
                                {% if round.id == game.round_id %}
                                    <td>
                                        <table class="table-index">
                                            <tr>
                                                {% if game.teamHome == Null %}

                                                    <td>{{ game.teamHomeAlias }} -- : -- {{ game.teamGuestAlias }}</td>
                                                {% else %}
                                                    <td><p class="text-center"><img class="img-responsive flag_small"
                                                                                    src="{{ game.teamHome.flag.url }}"/>{{ game.teamHome.short }}
                                                    </p>
                                                    </td>
                                                    {% if game.teamGuestGoals == Null %}
                                                        <td>-- : --</td>
                                                    {% else %}
                                                        <td><h4>{{ game.teamHomeGoals }}
                                                            : {{ game.teamGuestGoals }}</h4>
                                                            <p class="small">{{ game.others }}</p>
                                                        </td>
                                                    {% endif %}
                                                    <td><p class="text-center"><img
                                                            class="img-responsive flag_small"
                                                            src="{{ game.teamGuest.flag.url }}"/>{{ game.teamGuest.short }}
                                                    </p></td>
                                                {% endif %}
                                            </tr>
                                        </table>
                                    <td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    </table>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

em16/templates/em16/round-detail.html
{% extends "em16/base.html" %}
{% load staticfiles %}

{% block head %}
        <title> {{ round.name }} - EM 2016 in Frankreich</title>
{% endblock %}

{% block content %}

    <div class="row title">
        <h5><a href="{% url 'em16:index' %}">Spiele</a> >> {{ round.name }}</h5>
    </div>
    <div class="row">
        <div class="row">
        {% include 'em16/include/nav_round_snippet.html'%}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 ">
            {% include 'em16/include/game_list_snippet.html' %}
        </div>
    </div>
{% endblock %}

em16/templates/em16/settings-game-edit.html
{% extends "em16/base.html" %}
{% block head %}
    <title> Spielplan - EM 2016 in Frankreich</title>
{% endblock %}


{% block content %}
    <div class="row title">
        <h5><a href="{% url 'em16:setting-list' %}">Einstellungen</a> >> Spielplan | <span
                class="small">bearbeiten</span></h5>
    </div>
    <div class="row">
        <div class="col-lg-10 ">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Datum/Uhrzeit</th>
                    <th>Runde</th>
                    <th>Auslosung/Ergebnis</th>
                    <th>Optionen</th>
                </tr>
                </thead>
                <tbody>
                {% for game in games %}

                    <tr>
                        <td>
                            <p class="text-center"><strong>{{ game.date }} |</strong> {{ game.time }}</p>
                        </td>
                        <td>
                            <p>{{ game.round }}</p>
                        </td>
                        {% if game.teamHome.id != Null %}
                            <td>
                                <p class="text-info">{{ game.teamHome.short }}
                                    {% if game.teamGuestGoals == Null %}
                                        -- : --
                                    {% else %}
                                        {{ game.teamHomeGoals }} : {{ game.teamGuestGoals }}
                                    {% endif %}
                                    {{ game.teamGuest.short }}</p>
                            </td>
                        {% else %}
                            <td>
                                <p class="text-info">{{ game.teamHomeAlias }} : {{ game.teamGuestAlias }}</p>
                            </td>
                        {% endif %}
                        <td>
                            <a href="{% url 'em16:game-update' game.id %}" class="glyphicon glyphicon-edit btn btn-info"
                               title="Spiel bearbeiten"></a>

                            <a href="{% url 'em16:game-delete' game.id %}"
                               class="glyphicon glyphicon-trash btn btn-info" title="Spiel löschen"></a>
                        </td>
                    </tr>
                {% empty %}
                    <p>Keine Mannschaften zum bearbeiten gefunden.</p>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ block.super }}
{% endblock %}

em16/templates/em16/settings-team-edit.html
{% extends "em16/base.html" %}
{% block head %}
    <title> Teams - EM 2016 in Frankreich</title>
{% endblock %}


{% block content %}
    <div class="row title">
        <h5><a href="{% url 'em16:setting-list' %}">Einstellungen</a> >> Mannschaften | <span
                class="small">bearbeiten</span></h5>
    </div>

    {% include 'em16/include/messages.html' %}


    <div class="row">
        <div class="col-lg-10 ">
            {% for team in teams %}
                <div class="row">
                    <div class="col-lg-offset-1 col-lg-1">
                        <img class="img-responsive flag_small" src="{{ team.flag.url }}" alt="{{ team.name }}"/>
                    </div>
                    <div class=" col-lg-3">
                        <p class="text-left text-info">{{ team.name }} ({{ team.short }})</p>
                        <p class="small">Trainer: {{ team.trainer }}</p>
                    </div>
                    <div class="col-lg-2">
                        <a href="{% url 'em16:team-update' team.id %}" class="glyphicon glyphicon-edit btn btn-info"
                           title="Team bearbeiten"></a>

                        <a href="{% url 'em16:team-delete' team.id %}" class="glyphicon glyphicon-trash btn btn-info"
                           title="Team löschen"></a>
                    </div>

                </div>
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-2">
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-lg-offset-2">
                        <button class="glyphicon glyphicon-menu-down btn btn-xs bg-info" data-toggle="collapse"
                                data-target="#{{ team.name }} "></button>&emsp;
                        <span class="text-uppercase text-info">Spielerdetails</span>
                    </div>
                    <div class="col-lg-1 ">
                        <a href="{% url 'em16:player-create' team.id %}"
                           class="glyphicon glyphicon-plus btn btn-xs bg-info"
                           title="neuen Spieler zur Mannschaft hinzufügen"></a>
                    </div>
                    <div class="row">

                        <div id="{{ team.name }}" class="collapse col-lg-10 col-lg-offset-2 ">
                            <table class=" settings-player-list table-striped">
                                {% for player in players %}
                                    {% if team.id == player.team_id %}
                                        <tr>
                                            <td><img src="{{ player.img.url }}" alt="{{ player.surname }}"/></td>
                                            <td>{{ player.name }} {{ player.surname }} | {{ player.number }}</td>
                                            <td>{{ player.position }}</td>
                                            <td>
                                                <a href="{% url 'em16:player-update' player.id %}"
                                                   class="glyphicon glyphicon-edit btn btn-xs bg-info"
                                                   title="Spieler bearbeiten"></a>
                                                <a href="{% url 'em16:player-delete' player.id %}"
                                                   class="glyphicon glyphicon-trash btn btn-xs bg-info"
                                                   title="Spieler löschen"></a>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}

                            </table>

                        </div>
                    </div>
                </div>
                <hr class="settings-hr">

            {% empty %}
                <p>Keine Mannschaften zum bearbeiten gefunden.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ block.super }}
{% endblock %}

em16/templates/em16/settings.html
{% extends "em16/base.html" %}
{% block head %}
    <title> Settings - EM 2016 in Frankreich</title>
{% endblock %}

{% block content %}
    <div class="container-fluid title">
        <h3>Einstellungen</h3>
    </div>
    <div class="row settings">
        <div class="col-lg-2 col-lg-offset-2">
            <h4>Spielplan</h4>
            <span class="small">neue Spiele hinzufügen/ bearbeiten</span>
        </div>
        <div class="col-lg-2">
            <a href="{% url 'em16:game-create' %}" class="btn btn-info" title="Spiel hinzufügen"><i
                    class="glyphicon glyphicon-plus"></i></a>
            <a href="{% url 'em16:game-edit' %}" class="btn btn-info" title="Spiel bearbeiten"><i
                    class="glyphicon glyphicon-edit"></i></a>
        </div>

    </div>
    <hr>
    <div class="row settings">
        <div class="col-lg-2 col-lg-offset-2">
            <h4>Gruppen (A-F)</h4>
            <span class="small">Spielergebnisse Gruppenphase bearbeiten</span>
        </div>
        <div class="col-lg-2">
            <a href="{% url 'em16:group-edit' %}" class="btn btn-info" title="Gruppen bearbeiten"><i
                    class="glyphicon glyphicon-edit"></i></a>
        </div>
    </div>
    <hr>
    <div class="row settings">
        <div class="col-lg-2 col-lg-offset-2">
            <h4>Teams</h4>
            <span class="small">teilnehmende Mannschaften hinzufügen/ bearbeiten</span>
        </div>
        <div class="col-lg-2">
            <a href="{% url 'em16:team-create' %}" class="btn btn-info" title="Team hinzufügen"><i
                    class="glyphicon glyphicon-plus"></i></a>
            <a href="{% url 'em16:team-edit' %}" class="btn btn-info" title="Team bearbeiten"><i
                    class="glyphicon glyphicon-edit"></i></a>
        </div>
    </div>
    <hr>

{% endblock %}







{% block footer %}
    {{ block.super }}
{% endblock %}